### ISSUE TITLE
Do you need confluence?

### ISSUE THREAD

**Issue by patricksimonian** [CondeNast/fyi#71]
I noticed the install docs mentions setting up a confluence org. This is a requirement that ends up costing $$$ for larger organizations. 

I was wondering what this dependency is for and if it can be skipped :) ?

**Comment by johnkpaul** [comment]
It sadly cannot be skipped. This was built for the use case we have at CondeNast and doesn't currently have that flexibility.

**Comment by patricksimonian** [comment]
From an architectural standpoint, what does Confluence, as a component in FYI, used for? I'm just wondering if there is some point of collaboration here that our organization could provide to open it up a bit more

**Comment by johnkpaul** [comment]
Confluence is the editing interface and source of truth/data for FYI content. This project does not have a CMS included.

**Comment by patricksimonian** [comment]
Ah I understand. We will take a look into this and see if there's some way we can extend it to leverage headless cms like contentful or strapi. Thanks for the insight!
